SET @key_str = unhex(sha2('passphrase', 512));

/* ============================== */
/* insert ROLE */
/* ============================== */
INSERT INTO ROLE VALUES ('R000', 'Administrator');
INSERT INTO ROLE VALUES ('R001', 'Teacher');


/* ============================== */
/* insert SCHOOL */
/* ============================== */
INSERT INTO SCHOOL VALUES ('S000', 'Apple');
INSERT INTO SCHOOL VALUES ('S001', 'Butter');


/* ============================== */
/* insert USER */
/* ============================== */
INSERT INTO USER VALUES ('U000', 'Robert Walter', hex(AES_ENCRYPT('christopher12@richards-hudson.biz', @key_str)), 'S000', '');
INSERT INTO USER VALUES ('U001', 'Charles Mills', hex(AES_ENCRYPT('robinsonalan@yahoo.com', @key_str)), 'S000', '');
INSERT INTO USER VALUES ('U002', 'Gabriela Garrison', hex(AES_ENCRYPT('katelyn71@hotmail.com', @key_str)), 'S000', '');
INSERT INTO USER VALUES ('U003', 'Joseph Glover', hex(AES_ENCRYPT('mannjulia@yahoo.com', @key_str)), 'S000', '');
INSERT INTO USER VALUES ('U004', 'David Sanchez', hex(AES_ENCRYPT('trevinodaniel@trevino-torres.com', @key_str)), 'S000', '');
INSERT INTO USER VALUES ('U005', 'Yvonne Williams', hex(AES_ENCRYPT('david97@hotmail.com', @key_str)), 'S000', 'U000');
INSERT INTO USER VALUES ('U006', 'Michelle Morales', hex(AES_ENCRYPT('peter29@gmail.com', @key_str)), 'S000', 'U003');
INSERT INTO USER VALUES ('U007', 'Mark French', hex(AES_ENCRYPT('barnetttanner@king.net', @key_str)), 'S000', 'U003');
INSERT INTO USER VALUES ('U008', 'Chad Cuevas', hex(AES_ENCRYPT('jasonnichols@yahoo.com', @key_str)), 'S000', 'U004');
INSERT INTO USER VALUES ('U009', 'Steven George', hex(AES_ENCRYPT('kford@gmail.com', @key_str)), 'S000', 'U003');
INSERT INTO USER VALUES ('U010', 'Charles Johnson', hex(AES_ENCRYPT('woodsjeffrey@hobbs.com', @key_str)), 'S000', 'U003');
INSERT INTO USER VALUES ('U011', 'Stephanie Copeland', hex(AES_ENCRYPT('batesvictoria@gmail.com', @key_str)), 'S000', 'U001');
INSERT INTO USER VALUES ('U012', 'Grant Long', hex(AES_ENCRYPT('nwilson@ramirez-miller.com', @key_str)), 'S000', 'U001');
INSERT INTO USER VALUES ('U013', 'Lori Colon', hex(AES_ENCRYPT('diane90@hotmail.com', @key_str)), 'S000', 'U004');
INSERT INTO USER VALUES ('U014', 'Douglas Neal', hex(AES_ENCRYPT('stownsend@mcneil-reyes.org', @key_str)), 'S000', 'U000');
INSERT INTO USER VALUES ('U015', 'William Fletcher', hex(AES_ENCRYPT('dparker@watson.net', @key_str)), 'S000', 'U001');
INSERT INTO USER VALUES ('U016', 'Kimberly White', hex(AES_ENCRYPT('williamskari@yahoo.com', @key_str)), 'S000', 'U002');
INSERT INTO USER VALUES ('U017', 'Roger Smith', hex(AES_ENCRYPT('mary88@coleman.com', @key_str)), 'S000', 'U004');
INSERT INTO USER VALUES ('U018', 'Joshua Schroeder', hex(AES_ENCRYPT('tony49@keith.com', @key_str)), 'S000', 'U004');
INSERT INTO USER VALUES ('U019', 'Dr. Michael Black', hex(AES_ENCRYPT('marcuswhite@long.com', @key_str)), 'S000', 'U000');
INSERT INTO USER VALUES ('U020', 'Edward Sullivan', hex(AES_ENCRYPT('marissabrown@miller.org', @key_str)), 'S000', 'U002');
INSERT INTO USER VALUES ('U021', 'Erika Murphy', hex(AES_ENCRYPT('freychristopher@wilson.info', @key_str)), 'S000', 'U000');
INSERT INTO USER VALUES ('U022', 'Ashley Riley', hex(AES_ENCRYPT('howardjohnson@foster-gonzalez.com', @key_str)), 'S000', 'U003');
INSERT INTO USER VALUES ('U023', 'Heather Flowers', hex(AES_ENCRYPT('dennisjackson@torres.com', @key_str)), 'S000', 'U000');
INSERT INTO USER VALUES ('U024', 'Dr. Elizabeth Williamson', hex(AES_ENCRYPT('daniel36@hotmail.com', @key_str)), 'S000', 'U001');
INSERT INTO USER VALUES ('U025', 'Jacob Padilla', hex(AES_ENCRYPT('jonathanmckenzie@clark.com', @key_str)), 'S001', '');
INSERT INTO USER VALUES ('U026', 'Paige Hansen', hex(AES_ENCRYPT('jeffrey44@adams.com', @key_str)), 'S001', '');
INSERT INTO USER VALUES ('U027', 'Sarah Baker', hex(AES_ENCRYPT('hcochran@williams.com', @key_str)), 'S001', '');
INSERT INTO USER VALUES ('U028', 'Jeffery Kaiser', hex(AES_ENCRYPT('duncansarah@brown.biz', @key_str)), 'S001', '');
INSERT INTO USER VALUES ('U029', 'Ricky Moore', hex(AES_ENCRYPT('jennifersmith@dixon.com', @key_str)), 'S001', '');
INSERT INTO USER VALUES ('U030', 'Jaime Kelly', hex(AES_ENCRYPT('jennifer62@gardner.com', @key_str)), 'S001', 'U028');
INSERT INTO USER VALUES ('U031', 'Melanie Thompson', hex(AES_ENCRYPT('jennifer02@rivera.com', @key_str)), 'S001', 'U028');
INSERT INTO USER VALUES ('U032', 'Michelle Summers', hex(AES_ENCRYPT('qhernandez@curtis.com', @key_str)), 'S001', 'U029');
INSERT INTO USER VALUES ('U033', 'Rebecca Fitzgerald', hex(AES_ENCRYPT('jonesryan@yahoo.com', @key_str)), 'S001', 'U028');
INSERT INTO USER VALUES ('U034', 'Shirley Fleming', hex(AES_ENCRYPT('denise05@ortega-johnson.biz', @key_str)), 'S001', 'U029');
INSERT INTO USER VALUES ('U035', 'Emily Haynes', hex(AES_ENCRYPT('oramirez@yahoo.com', @key_str)), 'S001', 'U027');
INSERT INTO USER VALUES ('U036', 'Mrs. Sara Duncan', hex(AES_ENCRYPT('josephperez@mcgrath.com', @key_str)), 'S001', 'U028');
INSERT INTO USER VALUES ('U037', 'Ashley Johnson', hex(AES_ENCRYPT('tsmith@gmail.com', @key_str)), 'S001', 'U029');
INSERT INTO USER VALUES ('U038', 'Jessica Gonzalez', hex(AES_ENCRYPT('johnsondustin@hotmail.com', @key_str)), 'S001', 'U025');
INSERT INTO USER VALUES ('U039', 'Jesse Thomas', hex(AES_ENCRYPT('ohall@yahoo.com', @key_str)), 'S001', 'U028');
INSERT INTO USER VALUES ('U040', 'Amanda Orozco', hex(AES_ENCRYPT('emily11@harper.com', @key_str)), 'S001', 'U026');
INSERT INTO USER VALUES ('U041', 'Tiffany Smith', hex(AES_ENCRYPT('krausetimothy@peterson.com', @key_str)), 'S001', 'U028');
INSERT INTO USER VALUES ('U042', 'Nicholas Oconnor', hex(AES_ENCRYPT('leblancbrandy@yahoo.com', @key_str)), 'S001', 'U026');
INSERT INTO USER VALUES ('U043', 'Lisa James', hex(AES_ENCRYPT('stephenschmidt@kennedy.info', @key_str)), 'S001', 'U026');
INSERT INTO USER VALUES ('U044', 'Rita Luna', hex(AES_ENCRYPT('charlotte44@gmail.com', @key_str)), 'S001', 'U027');
INSERT INTO USER VALUES ('U045', 'Aimee Smith', hex(AES_ENCRYPT('nunezashley@yahoo.com', @key_str)), 'S001', 'U028');
INSERT INTO USER VALUES ('U046', 'Alan Peterson', hex(AES_ENCRYPT('jonathan25@roach-brown.com', @key_str)), 'S001', 'U028');
INSERT INTO USER VALUES ('U047', 'Jennifer Pope', hex(AES_ENCRYPT('ericadams@rivera.com', @key_str)), 'S001', 'U028');
INSERT INTO USER VALUES ('U048', 'Jason Fuller', hex(AES_ENCRYPT('anthony01@yahoo.com', @key_str)), 'S001', 'U026');
INSERT INTO USER VALUES ('U049', 'Maureen Torres', hex(AES_ENCRYPT('jennifer18@johnson.com', @key_str)), 'S001', 'U025');

/* ============================== */
/* insert REPORT_CARD */
/* ============================== */
INSERT INTO REPORT_CARD VALUES ('R000', 'U000', 'U003', 'U002', 'Pull firm bill experience agency.');
INSERT INTO REPORT_CARD VALUES ('R001', 'U001', 'U000', 'U004', 'Speech mind major rule goal degree medical serve.');
INSERT INTO REPORT_CARD VALUES ('R002', 'U002', 'U003', 'U004', 'Player everything choose rock age land establish.');
INSERT INTO REPORT_CARD VALUES ('R003', 'U003', 'U001', 'U003', 'Win understand then around ever require no.');
INSERT INTO REPORT_CARD VALUES ('R004', 'U004', 'U002', 'U000', 'Street wear local accept condition young college.');
INSERT INTO REPORT_CARD VALUES ('R005', 'U005', 'U001', 'U002', 'Suffer represent management else sing.');
INSERT INTO REPORT_CARD VALUES ('R006', 'U006', 'U002', 'U000', 'But reality specific. Agree set whatever around.');
INSERT INTO REPORT_CARD VALUES ('R007', 'U007', 'U002', 'U001', 'Later pull option phone PM message top.');
INSERT INTO REPORT_CARD VALUES ('R008', 'U008', 'U000', 'U004', 'Thought sound task nothing. To state field.');
INSERT INTO REPORT_CARD VALUES ('R009', 'U009', 'U000', 'U001', 'Fight her sell friend.');
INSERT INTO REPORT_CARD VALUES ('R010', 'U010', 'U001', 'U002', 'Finally marriage get live be.');
INSERT INTO REPORT_CARD VALUES ('R011', 'U011', 'U002', 'U000', 'Lawyer recognize speak beat church sort.');
INSERT INTO REPORT_CARD VALUES ('R012', 'U012', 'U000', 'U001', 'No that region feeling large like affect.');
INSERT INTO REPORT_CARD VALUES ('R013', 'U013', 'U004', 'U003', 'Rest traditional near art significant wide all.');
INSERT INTO REPORT_CARD VALUES ('R014', 'U014', 'U000', 'U000', 'Describe treat economy none south official.');
INSERT INTO REPORT_CARD VALUES ('R015', 'U015', 'U004', 'U003', 'Very also central section join course same.');
INSERT INTO REPORT_CARD VALUES ('R016', 'U016', 'U003', 'U000', 'Week spring Republican city understand.');
INSERT INTO REPORT_CARD VALUES ('R017', 'U017', 'U001', 'U002', 'Member recently consider.');
INSERT INTO REPORT_CARD VALUES ('R018', 'U018', 'U001', 'U002', 'Idea really join tell attorney.');
INSERT INTO REPORT_CARD VALUES ('R019', 'U019', 'U000', 'U002', 'Box their throw kind.');
INSERT INTO REPORT_CARD VALUES ('R020', 'U020', 'U004', 'U001', 'Which high if couple.');
INSERT INTO REPORT_CARD VALUES ('R021', 'U021', 'U001', 'U000', 'Room their will charge kid fear research.');
INSERT INTO REPORT_CARD VALUES ('R022', 'U022', 'U004', 'U003', 'Rock pretty section.');
INSERT INTO REPORT_CARD VALUES ('R023', 'U023', 'U002', 'U001', 'Several sense type blood catch. See mouth big.');
INSERT INTO REPORT_CARD VALUES ('R024', 'U024', 'U004', 'U004', 'Girl factor wall reduce.');
INSERT INTO REPORT_CARD VALUES ('R025', 'U025', 'U025', 'U026', 'Power fear what produce room side religious.');
INSERT INTO REPORT_CARD VALUES ('R026', 'U026', 'U028', 'U026', 'Member oil when purpose mention.');
INSERT INTO REPORT_CARD VALUES ('R027', 'U027', 'U027', 'U025', 'Long far woman fund.');
INSERT INTO REPORT_CARD VALUES ('R028', 'U028', 'U029', 'U025', 'Perhaps each public TV. Soon able improve cold.');
INSERT INTO REPORT_CARD VALUES ('R029', 'U029', 'U027', 'U026', 'For war onto large single.');
INSERT INTO REPORT_CARD VALUES ('R030', 'U030', 'U028', 'U027', 'Run life bring someone.');
INSERT INTO REPORT_CARD VALUES ('R031', 'U031', 'U028', 'U028', 'Need maybe guy entire whole sign cell house.');
INSERT INTO REPORT_CARD VALUES ('R032', 'U032', 'U029', 'U028', 'Mother financial draw movie national.');
INSERT INTO REPORT_CARD VALUES ('R033', 'U033', 'U027', 'U027', 'Actually need lot even individual quite.');
INSERT INTO REPORT_CARD VALUES ('R034', 'U034', 'U027', 'U025', 'Day represent vote safe should.');
INSERT INTO REPORT_CARD VALUES ('R035', 'U035', 'U028', 'U029', 'Moment yes scene small alone just hold.');
INSERT INTO REPORT_CARD VALUES ('R036', 'U036', 'U028', 'U028', 'Own us yet project early suffer high.');
INSERT INTO REPORT_CARD VALUES ('R037', 'U037', 'U028', 'U025', 'Main pick no common red hour.');
INSERT INTO REPORT_CARD VALUES ('R038', 'U038', 'U029', 'U026', 'Market whose forward close. Real put issue.');
INSERT INTO REPORT_CARD VALUES ('R039', 'U039', 'U026', 'U028', 'Many feel hard listen.');
INSERT INTO REPORT_CARD VALUES ('R040', 'U040', 'U028', 'U026', 'Candidate speech trade draw there plan employee.');
INSERT INTO REPORT_CARD VALUES ('R041', 'U041', 'U025', 'U029', 'Message nothing loss magazine still.');
INSERT INTO REPORT_CARD VALUES ('R042', 'U042', 'U027', 'U025', 'Theory population would.');
INSERT INTO REPORT_CARD VALUES ('R043', 'U043', 'U029', 'U027', 'Tonight organization hand field up.');
INSERT INTO REPORT_CARD VALUES ('R044', 'U044', 'U028', 'U028', 'Game along each offer politics.');
INSERT INTO REPORT_CARD VALUES ('R045', 'U045', 'U027', 'U028', 'Continue real perform use plant.');
INSERT INTO REPORT_CARD VALUES ('R046', 'U046', 'U025', 'U028', 'Inside grow agency claim. Democratic certain son.');
INSERT INTO REPORT_CARD VALUES ('R047', 'U047', 'U028', 'U028', 'Central away standard color sure.');
INSERT INTO REPORT_CARD VALUES ('R048', 'U048', 'U027', 'U027', 'Same everyone result become.');
INSERT INTO REPORT_CARD VALUES ('R049', 'U049', 'U028', 'U026', 'Board identify event few relate.');


/* ============================== */
/* insert SUBJECT */
/* ============================== */
INSERT INTO SUBJECT VALUES ('S000', 'R000', 'English');
INSERT INTO SUBJECT VALUES ('S050', 'R000', 'Math');
INSERT INTO SUBJECT VALUES ('S100', 'R000', 'Science');
INSERT INTO SUBJECT VALUES ('S150', 'R000', 'Social');
INSERT INTO SUBJECT VALUES ('S001', 'R001', 'English');
INSERT INTO SUBJECT VALUES ('S051', 'R001', 'Math');
INSERT INTO SUBJECT VALUES ('S101', 'R001', 'Science');
INSERT INTO SUBJECT VALUES ('S151', 'R001', 'Social');
INSERT INTO SUBJECT VALUES ('S002', 'R002', 'English');
INSERT INTO SUBJECT VALUES ('S052', 'R002', 'Math');
INSERT INTO SUBJECT VALUES ('S102', 'R002', 'Science');
INSERT INTO SUBJECT VALUES ('S152', 'R002', 'Social');
INSERT INTO SUBJECT VALUES ('S003', 'R003', 'English');
INSERT INTO SUBJECT VALUES ('S053', 'R003', 'Math');
INSERT INTO SUBJECT VALUES ('S103', 'R003', 'Science');
INSERT INTO SUBJECT VALUES ('S153', 'R003', 'Social');
INSERT INTO SUBJECT VALUES ('S004', 'R004', 'English');
INSERT INTO SUBJECT VALUES ('S054', 'R004', 'Math');
INSERT INTO SUBJECT VALUES ('S104', 'R004', 'Science');
INSERT INTO SUBJECT VALUES ('S154', 'R004', 'Social');
INSERT INTO SUBJECT VALUES ('S005', 'R005', 'English');
INSERT INTO SUBJECT VALUES ('S055', 'R005', 'Math');
INSERT INTO SUBJECT VALUES ('S105', 'R005', 'Science');
INSERT INTO SUBJECT VALUES ('S155', 'R005', 'Social');
INSERT INTO SUBJECT VALUES ('S006', 'R006', 'English');
INSERT INTO SUBJECT VALUES ('S056', 'R006', 'Math');
INSERT INTO SUBJECT VALUES ('S106', 'R006', 'Science');
INSERT INTO SUBJECT VALUES ('S156', 'R006', 'Social');
INSERT INTO SUBJECT VALUES ('S007', 'R007', 'English');
INSERT INTO SUBJECT VALUES ('S057', 'R007', 'Math');
INSERT INTO SUBJECT VALUES ('S107', 'R007', 'Science');
INSERT INTO SUBJECT VALUES ('S157', 'R007', 'Social');
INSERT INTO SUBJECT VALUES ('S008', 'R008', 'English');
INSERT INTO SUBJECT VALUES ('S058', 'R008', 'Math');
INSERT INTO SUBJECT VALUES ('S108', 'R008', 'Science');
INSERT INTO SUBJECT VALUES ('S158', 'R008', 'Social');
INSERT INTO SUBJECT VALUES ('S009', 'R009', 'English');
INSERT INTO SUBJECT VALUES ('S059', 'R009', 'Math');
INSERT INTO SUBJECT VALUES ('S109', 'R009', 'Science');
INSERT INTO SUBJECT VALUES ('S159', 'R009', 'Social');
INSERT INTO SUBJECT VALUES ('S010', 'R010', 'English');
INSERT INTO SUBJECT VALUES ('S060', 'R010', 'Math');
INSERT INTO SUBJECT VALUES ('S110', 'R010', 'Science');
INSERT INTO SUBJECT VALUES ('S160', 'R010', 'Social');
INSERT INTO SUBJECT VALUES ('S011', 'R011', 'English');
INSERT INTO SUBJECT VALUES ('S061', 'R011', 'Math');
INSERT INTO SUBJECT VALUES ('S111', 'R011', 'Science');
INSERT INTO SUBJECT VALUES ('S161', 'R011', 'Social');
INSERT INTO SUBJECT VALUES ('S012', 'R012', 'English');
INSERT INTO SUBJECT VALUES ('S062', 'R012', 'Math');
INSERT INTO SUBJECT VALUES ('S112', 'R012', 'Science');
INSERT INTO SUBJECT VALUES ('S162', 'R012', 'Social');
INSERT INTO SUBJECT VALUES ('S013', 'R013', 'English');
INSERT INTO SUBJECT VALUES ('S063', 'R013', 'Math');
INSERT INTO SUBJECT VALUES ('S113', 'R013', 'Science');
INSERT INTO SUBJECT VALUES ('S163', 'R013', 'Social');
INSERT INTO SUBJECT VALUES ('S014', 'R014', 'English');
INSERT INTO SUBJECT VALUES ('S064', 'R014', 'Math');
INSERT INTO SUBJECT VALUES ('S114', 'R014', 'Science');
INSERT INTO SUBJECT VALUES ('S164', 'R014', 'Social');
INSERT INTO SUBJECT VALUES ('S015', 'R015', 'English');
INSERT INTO SUBJECT VALUES ('S065', 'R015', 'Math');
INSERT INTO SUBJECT VALUES ('S115', 'R015', 'Science');
INSERT INTO SUBJECT VALUES ('S165', 'R015', 'Social');
INSERT INTO SUBJECT VALUES ('S016', 'R016', 'English');
INSERT INTO SUBJECT VALUES ('S066', 'R016', 'Math');
INSERT INTO SUBJECT VALUES ('S116', 'R016', 'Science');
INSERT INTO SUBJECT VALUES ('S166', 'R016', 'Social');
INSERT INTO SUBJECT VALUES ('S017', 'R017', 'English');
INSERT INTO SUBJECT VALUES ('S067', 'R017', 'Math');
INSERT INTO SUBJECT VALUES ('S117', 'R017', 'Science');
INSERT INTO SUBJECT VALUES ('S167', 'R017', 'Social');
INSERT INTO SUBJECT VALUES ('S018', 'R018', 'English');
INSERT INTO SUBJECT VALUES ('S068', 'R018', 'Math');
INSERT INTO SUBJECT VALUES ('S118', 'R018', 'Science');
INSERT INTO SUBJECT VALUES ('S168', 'R018', 'Social');
INSERT INTO SUBJECT VALUES ('S019', 'R019', 'English');
INSERT INTO SUBJECT VALUES ('S069', 'R019', 'Math');
INSERT INTO SUBJECT VALUES ('S119', 'R019', 'Science');
INSERT INTO SUBJECT VALUES ('S169', 'R019', 'Social');
INSERT INTO SUBJECT VALUES ('S020', 'R020', 'English');
INSERT INTO SUBJECT VALUES ('S070', 'R020', 'Math');
INSERT INTO SUBJECT VALUES ('S120', 'R020', 'Science');
INSERT INTO SUBJECT VALUES ('S170', 'R020', 'Social');
INSERT INTO SUBJECT VALUES ('S021', 'R021', 'English');
INSERT INTO SUBJECT VALUES ('S071', 'R021', 'Math');
INSERT INTO SUBJECT VALUES ('S121', 'R021', 'Science');
INSERT INTO SUBJECT VALUES ('S171', 'R021', 'Social');
INSERT INTO SUBJECT VALUES ('S022', 'R022', 'English');
INSERT INTO SUBJECT VALUES ('S072', 'R022', 'Math');
INSERT INTO SUBJECT VALUES ('S122', 'R022', 'Science');
INSERT INTO SUBJECT VALUES ('S172', 'R022', 'Social');
INSERT INTO SUBJECT VALUES ('S023', 'R023', 'English');
INSERT INTO SUBJECT VALUES ('S073', 'R023', 'Math');
INSERT INTO SUBJECT VALUES ('S123', 'R023', 'Science');
INSERT INTO SUBJECT VALUES ('S173', 'R023', 'Social');
INSERT INTO SUBJECT VALUES ('S024', 'R024', 'English');
INSERT INTO SUBJECT VALUES ('S074', 'R024', 'Math');
INSERT INTO SUBJECT VALUES ('S124', 'R024', 'Science');
INSERT INTO SUBJECT VALUES ('S174', 'R024', 'Social');
INSERT INTO SUBJECT VALUES ('S025', 'R025', 'English');
INSERT INTO SUBJECT VALUES ('S075', 'R025', 'Math');
INSERT INTO SUBJECT VALUES ('S125', 'R025', 'Science');
INSERT INTO SUBJECT VALUES ('S175', 'R025', 'Social');
INSERT INTO SUBJECT VALUES ('S026', 'R026', 'English');
INSERT INTO SUBJECT VALUES ('S076', 'R026', 'Math');
INSERT INTO SUBJECT VALUES ('S126', 'R026', 'Science');
INSERT INTO SUBJECT VALUES ('S176', 'R026', 'Social');
INSERT INTO SUBJECT VALUES ('S027', 'R027', 'English');
INSERT INTO SUBJECT VALUES ('S077', 'R027', 'Math');
INSERT INTO SUBJECT VALUES ('S127', 'R027', 'Science');
INSERT INTO SUBJECT VALUES ('S177', 'R027', 'Social');
INSERT INTO SUBJECT VALUES ('S028', 'R028', 'English');
INSERT INTO SUBJECT VALUES ('S078', 'R028', 'Math');
INSERT INTO SUBJECT VALUES ('S128', 'R028', 'Science');
INSERT INTO SUBJECT VALUES ('S178', 'R028', 'Social');
INSERT INTO SUBJECT VALUES ('S029', 'R029', 'English');
INSERT INTO SUBJECT VALUES ('S079', 'R029', 'Math');
INSERT INTO SUBJECT VALUES ('S129', 'R029', 'Science');
INSERT INTO SUBJECT VALUES ('S179', 'R029', 'Social');
INSERT INTO SUBJECT VALUES ('S030', 'R030', 'English');
INSERT INTO SUBJECT VALUES ('S080', 'R030', 'Math');
INSERT INTO SUBJECT VALUES ('S130', 'R030', 'Science');
INSERT INTO SUBJECT VALUES ('S180', 'R030', 'Social');
INSERT INTO SUBJECT VALUES ('S031', 'R031', 'English');
INSERT INTO SUBJECT VALUES ('S081', 'R031', 'Math');
INSERT INTO SUBJECT VALUES ('S131', 'R031', 'Science');
INSERT INTO SUBJECT VALUES ('S181', 'R031', 'Social');
INSERT INTO SUBJECT VALUES ('S032', 'R032', 'English');
INSERT INTO SUBJECT VALUES ('S082', 'R032', 'Math');
INSERT INTO SUBJECT VALUES ('S132', 'R032', 'Science');
INSERT INTO SUBJECT VALUES ('S182', 'R032', 'Social');
INSERT INTO SUBJECT VALUES ('S033', 'R033', 'English');
INSERT INTO SUBJECT VALUES ('S083', 'R033', 'Math');
INSERT INTO SUBJECT VALUES ('S133', 'R033', 'Science');
INSERT INTO SUBJECT VALUES ('S183', 'R033', 'Social');
INSERT INTO SUBJECT VALUES ('S034', 'R034', 'English');
INSERT INTO SUBJECT VALUES ('S084', 'R034', 'Math');
INSERT INTO SUBJECT VALUES ('S134', 'R034', 'Science');
INSERT INTO SUBJECT VALUES ('S184', 'R034', 'Social');
INSERT INTO SUBJECT VALUES ('S035', 'R035', 'English');
INSERT INTO SUBJECT VALUES ('S085', 'R035', 'Math');
INSERT INTO SUBJECT VALUES ('S135', 'R035', 'Science');
INSERT INTO SUBJECT VALUES ('S185', 'R035', 'Social');
INSERT INTO SUBJECT VALUES ('S036', 'R036', 'English');
INSERT INTO SUBJECT VALUES ('S086', 'R036', 'Math');
INSERT INTO SUBJECT VALUES ('S136', 'R036', 'Science');
INSERT INTO SUBJECT VALUES ('S186', 'R036', 'Social');
INSERT INTO SUBJECT VALUES ('S037', 'R037', 'English');
INSERT INTO SUBJECT VALUES ('S087', 'R037', 'Math');
INSERT INTO SUBJECT VALUES ('S137', 'R037', 'Science');
INSERT INTO SUBJECT VALUES ('S187', 'R037', 'Social');
INSERT INTO SUBJECT VALUES ('S038', 'R038', 'English');
INSERT INTO SUBJECT VALUES ('S088', 'R038', 'Math');
INSERT INTO SUBJECT VALUES ('S138', 'R038', 'Science');
INSERT INTO SUBJECT VALUES ('S188', 'R038', 'Social');
INSERT INTO SUBJECT VALUES ('S039', 'R039', 'English');
INSERT INTO SUBJECT VALUES ('S089', 'R039', 'Math');
INSERT INTO SUBJECT VALUES ('S139', 'R039', 'Science');
INSERT INTO SUBJECT VALUES ('S189', 'R039', 'Social');
INSERT INTO SUBJECT VALUES ('S040', 'R040', 'English');
INSERT INTO SUBJECT VALUES ('S090', 'R040', 'Math');
INSERT INTO SUBJECT VALUES ('S140', 'R040', 'Science');
INSERT INTO SUBJECT VALUES ('S190', 'R040', 'Social');
INSERT INTO SUBJECT VALUES ('S041', 'R041', 'English');
INSERT INTO SUBJECT VALUES ('S091', 'R041', 'Math');
INSERT INTO SUBJECT VALUES ('S141', 'R041', 'Science');
INSERT INTO SUBJECT VALUES ('S191', 'R041', 'Social');
INSERT INTO SUBJECT VALUES ('S042', 'R042', 'English');
INSERT INTO SUBJECT VALUES ('S092', 'R042', 'Math');
INSERT INTO SUBJECT VALUES ('S142', 'R042', 'Science');
INSERT INTO SUBJECT VALUES ('S192', 'R042', 'Social');
INSERT INTO SUBJECT VALUES ('S043', 'R043', 'English');
INSERT INTO SUBJECT VALUES ('S093', 'R043', 'Math');
INSERT INTO SUBJECT VALUES ('S143', 'R043', 'Science');
INSERT INTO SUBJECT VALUES ('S193', 'R043', 'Social');
INSERT INTO SUBJECT VALUES ('S044', 'R044', 'English');
INSERT INTO SUBJECT VALUES ('S094', 'R044', 'Math');
INSERT INTO SUBJECT VALUES ('S144', 'R044', 'Science');
INSERT INTO SUBJECT VALUES ('S194', 'R044', 'Social');
INSERT INTO SUBJECT VALUES ('S045', 'R045', 'English');
INSERT INTO SUBJECT VALUES ('S095', 'R045', 'Math');
INSERT INTO SUBJECT VALUES ('S145', 'R045', 'Science');
INSERT INTO SUBJECT VALUES ('S195', 'R045', 'Social');
INSERT INTO SUBJECT VALUES ('S046', 'R046', 'English');
INSERT INTO SUBJECT VALUES ('S096', 'R046', 'Math');
INSERT INTO SUBJECT VALUES ('S146', 'R046', 'Science');
INSERT INTO SUBJECT VALUES ('S196', 'R046', 'Social');
INSERT INTO SUBJECT VALUES ('S047', 'R047', 'English');
INSERT INTO SUBJECT VALUES ('S097', 'R047', 'Math');
INSERT INTO SUBJECT VALUES ('S147', 'R047', 'Science');
INSERT INTO SUBJECT VALUES ('S197', 'R047', 'Social');
INSERT INTO SUBJECT VALUES ('S048', 'R048', 'English');
INSERT INTO SUBJECT VALUES ('S098', 'R048', 'Math');
INSERT INTO SUBJECT VALUES ('S148', 'R048', 'Science');
INSERT INTO SUBJECT VALUES ('S198', 'R048', 'Social');
INSERT INTO SUBJECT VALUES ('S049', 'R049', 'English');
INSERT INTO SUBJECT VALUES ('S099', 'R049', 'Math');
INSERT INTO SUBJECT VALUES ('S149', 'R049', 'Science');
INSERT INTO SUBJECT VALUES ('S199', 'R049', 'Social');

/* ============================== */
/* Grant Teacher Role */
/* ============================== */
INSERT INTO USER_ROLE VALUES ('U000', 'R001');
INSERT INTO USER_ROLE VALUES ('U001', 'R001');
INSERT INTO USER_ROLE VALUES ('U002', 'R001');
INSERT INTO USER_ROLE VALUES ('U003', 'R001');
INSERT INTO USER_ROLE VALUES ('U004', 'R001');
INSERT INTO USER_ROLE VALUES ('U025', 'R001');
INSERT INTO USER_ROLE VALUES ('U026', 'R001');
INSERT INTO USER_ROLE VALUES ('U027', 'R001');
INSERT INTO USER_ROLE VALUES ('U028', 'R001');
INSERT INTO USER_ROLE VALUES ('U029', 'R001');


/* ============================== */
/* insert Admin User */
/* ============================== */
INSERT INTO SCHOOL VALUES ('0000', 'Admin');
INSERT INTO USER VALUES ('0000', 'Admin User', hex(AES_ENCRYPT('asdf@asdf.com', @key_str)), '0000', '');
INSERT INTO USER_ROLE VALUES ('0000', 'R000');
